### PR TITLE
yarn flatten

### PR DESCRIPTION
**Pull request by carletex**
`yarn flatten`: Allow to flatten contracts into a single file.

I think we could do the same in Foundry: https://book.getfoundry.sh/reference/forge/forge-flatten

Open to suggestions!

### CODE REVIEW

**Comment by technophile-04** [comment]
Thanks Carlos 🙌

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/33b65c64-9c57-43fe-b8ed-9cf7f0e85a8d



For some reason when I run just `yarn flatten` , the `FlattendContracts.sol` only contains output till max line 258 rest output is eaten up. 

When I `cd package/hardhat` and manually run `yarn hardhat flatten ...` it works just fine, not sure if  its just with my system. 

If the contract is small (eg. I removed import `console.log` from `YourContract.sol`) It works nicely not sure if its due some limit on no. of line redirect (">") into file when from package.json script. 

cc @Pabl0cks could you please give it a try, it might be something to do with my machine

**Comment by carletex** [comment]
Oh weird! @technophile-04 

What happens if you remove the redirect in the hardhat package.json? Do you get the full output in the console?

**Comment by carletex** [comment]
no clue what might be:man_shrugging: 

> yeah I do get full output in console if I remove redirect from package.json script

With this removed in the package.json, does this work? `yarn flatten > test.sol`

**Comment by technophile-04** [comment]
> yarn flatten > test.sol

Yup it creates `test.sol` at root of monorepo but works nicely ! 

Also if I put this in root package.json  `"flatten": "yarn workspace @se-2/hardhat flatten > test.sol",` it again breaks, so seems like an issue with redirect. 

Does it properly work for you? Lets maybe work for @Pabl0cks to test, I will also try to debug till then 🙌

**Comment by carletex** [comment]
> it again breaks, so seems like an issue with redirect.

I guess it's an issue with redirect inside the package.json, since the redirection works fine in your system (`yarn flatten > test.sol`)

> Does it properly work for you? Lets maybe work for @Pabl0cks to test, I will also try to debug till then 🙌

Yep, it works for me as it's.

AN alternative could be to skip the redirection and just print out on stdout... and people can redirect themselves.

**Comment by Pabl0cks** [comment]
> Does it properly work for you? Lets maybe work for @Pabl0cks to test, I will also try to debug till then 🙌

GJ Carlos and Shiv!! It's working fine to me, I get the same output with `yarn flatten` and with `yarn hardhat flatten > flattened.sol´ => 1648 lines and seems complete

**Review by Pabl0cks — APPROVED** [review]
Is working great to me, flattening all direct imports and imports into those imports

**Review by technophile-04 — APPROVED** [review]
> I guess it's an issue with redirect inside the package.json

💯💯

Hmm after some digging turns out something to do with yarn version (might be how I have globally configured `yarn`) 

When I do `yarn set version 1.22.19` It works nicely for me but for some reason it sets that version at project level :( 

<details>
<summary>
Demo Video 
</summary>


https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/7cd366f8-c624-4c18-9672-4cda46b5d12c

</details>


> AN alternative could be to skip the redirection and just print out on stdout

+1 for this, I think people can redirect themselves.... just to be safe, eg Autin intuitively doing [here](https://www.youtube.com/live/lmdj_QeqcdY?si=xGd1LItKh1rwegbZ&t=788)  

But please free to merge as it ! Tysm Carlos, and Pablo for test 🙌

Will create a PR adding this into foundry 🙌

**Comment by carletex** [comment]
> eg Autin intuitively doing [here](https://www.youtube.com/live/lmdj_QeqcdY?si=xGd1LItKh1rwegbZ&t=788)

Autocompletion for SE-1 haha where it was printed in stdout

Decided to remove the redirect in the script, in case someone else faces the same issue as Shiv

**Comment by technophile-04** [comment]
Tysm merge this 🙌

**Pull request merged**
