### PR TITLE
make use of tailwind `link`-class with some extensions

### PR DESCRIPTION
**Pull request by FilipHarald**
## Description

Changes so that the Footer uses `link` from tailwind. Also adding some customization to it.

## Additional Information

- [X] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [X] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Implements the feedback from @carletex here: https://github.com/scaffold-eth/scaffold-eth-2/pull/551

Your ENS/address: harmont.eth

### CODE REVIEW

**Comment by FilipHarald** [comment]
@carletex , I took the liberty of putting opacity `80%`, it wasn't visible in light-mode otherwise. Other than that I have implemented to what I think you meant.

I'm not sure if it's optimal to have the extension listed twice. But I didn't get it to work putting it just in the `config.theme.extend`. Perhaps you could point me in the right direction?

**Comment by carletex** [comment]
It's looking great @FilipHarald, thanks!

Could you fix the prettier issues? You should be able to configure your IDE so it gets our prettier config and apply it on save.

image

**Comment by FilipHarald** [comment]
Yepp, fixed it now. I have it working for `.ts`-files but for some reason it doesn't work for `.js`. But I'm sure that is on my own configs that needs some adjusting.

**Comment by carletex** [comment]
Good stuff @FilipHarald 

Thanks!!

**Review by carletex — APPROVED** [review]

**Pull request merged**
