### PR TITLE
Add polygonZkEvm and polygonZkEvmTestnet and update wagmi/core

### PR DESCRIPTION
**Pull request by OwlWilderness**
#310  Add polygonZkEvm and polygonZkEvmTestnet and update wagmi/core

- updated hardhat config ts to include zkevm main and test net
- updated wagmi/core to 12.10

### CODE REVIEW

**Comment by OwlWilderness** [comment]
Hi - this is my first functional PR - please guide me if i need to add / remove anything (like is the yarn.lock supposed to be included??)

**Comment by sverps** [comment]
`yarn.lock` should indeed be included :+1: 
Files that shouldn't be included are generally added to `.gitignore` already.

Will play around a bit with it to see if there's anything that needs to be taken into account with the `wagmi` update, but the PR looks clean :+1:

**Comment by OwlWilderness** [comment]
Thank you @sverps for your feedback!  

Please note I only deployed to testnet - working on bridging to deploy to mainnet tonight. (I probably should have waited to raise the pr until then maybe).
  I also haven't worked out verify but not sure if that is just a api-key issue. 

Thanks

**Comment by technophile-04** [comment]
Tysm @OwlWilderness, I think we should be really be conscious of package updation especially `wagmi` because we have overridden some types and not rely on the migration guide 😅, 

Saying this because I think Wagmi `0.12.8` have again broke `AddressType` checkout -> https://github.com/wagmi-dev/wagmi/issues/1712#issuecomment-1514888516

> Please note I only deployed to testnet - working on bridging to deploy to mainnet tonight. (I probably should have waited to raise the pr until then maybe).
Yup it would be really great if we get verify working

**Comment by OwlWilderness** [comment]
Hi @technophile-04 
Thank you for your help.  I've started to update the related issue (#310) with this feedback- and I will update as I deploy and verify. Thanks

**Review by technophile-04 — APPROVED** [review]
Hey tysm @OwlWilderness 🙌, We actually updated the wagmi version so reverted the other changes and just kept the `hardhat.config.ts` changes

**Comment by OwlWilderness** [comment]
Thank you @technophile-04! I knew wagmi was going in and thought to update this PR but wasn't paying too much attention - so I really appreciate you reverting those commits and merging this.

**Pull request merged**
