### PR TITLE
feat: adds zksync era testnet and mainnet

### PR DESCRIPTION
**Pull request by codenamejason**

### CODE REVIEW

**Comment by technophile-04** [comment]
Tysm Jason !! Since it requires additional packages like [hardhat-zksync-verify](https://era.zksync.io/docs/tools/hardhat/hardhat-zksync-verify.html) and others too also additional separate logic for deployments. I think could have it as a plugin -> check (#251) 🙌

Since we have got it referenced in (#251), closing this for now and we can come back to it later but tysm for this ! 🙌

**Comment by moltam89** [comment]
Hi @codenamejason , @technophile-04 ,

I started experimenting with zkSync and I thought it would be great if we could simply deploy to zkSync test and mainnet with scaffold-eth-2.

I found this PR and I could deploy a test contract to zkSync testnet.

I was wondering what we would need to merge this PR.
I don't really understand how https://github.com/scaffold-eth/scaffold-eth-2/issues/251 is connected.

Thanks,
Tamas

**Comment by codenamejason** [comment]
Not sure why we didn't move forward with this @moltam89

**Comment by technophile-04** [comment]
Actually looking at PR and Zskync docs it seemed it requires some specific zksync stuff need to be added...also for deployments we rely on `hardhat-deploy` generated `deployments` directory to provide auto TS autocompletion on frontend checkout( #368 ) and for more details checkout #202. We might again need to add zksync-specific logic in `99_generateTsAbis` too. So it didn't seem a good default for se-2 since we are trying hard to keep things minimal 

That's the reason it felt like an extension that can be added in #251

But please feel to reopen the PR clean-up things and if it looks minimal and well integrated without having much specific logic in the general file we can merge it to the `main` too !! or at least we can keep it in a different branch until #251 (we are not planning to have separate branches like how we have in SE-1 instead we planning to add stuff in #251 ) 

Hopefully, this makes sense 😅. Really sorry for closing the PR without more description 🙏 But please feel free to reopen  🙏

**Comment by moltam89** [comment]
Hey guys,

I think in the meantime zkSync support was added to hardhat-deploy.

According to the [zkSync docs](https://era.zksync.io/docs/tools/hardhat/migrating-to-zksync.html#deploy-contracts), hardhat-deploy version ^0.11.26 supports deployments on zkSync Era, I've sent a [PR](https://github.com/scaffold-eth/scaffold-eth-2/pull/383) to use it.

Best,
Tamas

**Pull request closed without merging**
