### PR TITLE
Remove Goerli from supported networks

### PR DESCRIPTION
**Pull request by Hotmanics**
## Description

Goerli has been effectively deprecated and is no longer supported by major RPC clients, thus we can safely remove it from the template as it appears as unnecessary fluff.

## Additional Information

- [ x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: JacobHomanics.eth

### CODE REVIEW

**Comment by carletex** [comment]
Thanks @Hotmanics!

Always feels good to remove stuff :D 

Could you remove other appearances of `goerli` in the codebase? 

- Deploy script (see the commented section). Maybe switch for sepolia.
- `networks.ts` on the next app

**Comment by Hotmanics** [comment]
> Thanks @Hotmanics!
> 
> Always feels good to remove stuff :D
> 
> Could you remove other appearances of `goerli` in the codebase?
> 
> * Deploy script (see the commented section). Maybe switch for sepolia.
> * `networks.ts` on the next app

ah great! Did not realize it was in those places. Thanks!

This PR now accounts for those files!

**Review by rin-st — APPROVED** [review]
lgtm!

**Review by technophile-04 — APPROVED** [review]
Thanks @Hotmanics , and also others for reviews and test looking good !

**Pull request merged**
