### PR TITLE
New shadow-center utility class for dropdown/notifications

### LINKED ISSUE #441: Better notifications / dropdowns
- I think the shadows in the notifications / dropdowns doesn't give them enough contrast.
-  I'm not sold on the rounded buttons inside the dropdown, something seems off.

I'll ask Andrea to see if we can make some improvements. I think we just need some subtle tweaks.

1.

---
2.

---
3.

### PR DESCRIPTION
**Pull request by carletex**
Fixes #441 

I discussed several options with Andrea, to make the dropdown / notifications look better (they were mixing with the background).

We ended up adding a new shadow utility class `shadow-center` that combined with a `shadow-accent` (or `shadow-{primary|secondary|etc..}) gives a nice effect.

Notifications:
Screenshot from 2023-07-27 12-23-25

Dropdown menu: (Also made the dropdown menu items smaller and adjust the border radius (we can also apply this to #446))

image

What do you all think?

### CODE REVIEW

**Comment by rin-st** [comment]
Looks good! But not for the dark theme

accent color: 
Снимок экрана 2023-07-27 в 19 25 33
Снимок экрана 2023-07-27 в 19 37 21

primary color: 
Снимок экрана 2023-07-27 в 19 33 56
Снимок экрана 2023-07-27 в 19 36 58

it seems we need to add new color for shadows

**Comment by carletex** [comment]
> Looks good! But not for the dark theme

What is wrong in the dark theme? I chose the `accent` since it was the best one (more contrast) in the dark theme.

main:
image

this pr:
image

main:
image

this pr:
image


---

In the notification, I think it looks better.

For the dropdown, maybe we could change the bg to bg-200, so it has more contrast:

image

---

Let's see what others think too.

**Review by technophile-04 — APPROVED** [review]
Looks cute and nice to me !! 

> For the dropdown, maybe we could change the bg to bg-200, so it has more contrast:

Yup, this looks better 

we have a glowy shadow in the light mode so in the dark mode having it too makes sense 

Darkmode also looks cool to me 🙌

**Comment by rin-st** [comment]
> For the dropdown, maybe we could change the bg to bg-200, so it has more contrast:

now it's better :)

**Review by rin-st — APPROVED** [review]

**Pull request merged**
