### PR TITLE
Follow root level naming convention as proposed in #977

### PR DESCRIPTION
**Pull request by schmidsi**
## Description

Changes root-level commands names to follow the `{package}:{command}` standard. Except some globally important commands: `yarn chain`, `yarn deploy`, `yarn start`.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #977_

Your ENS/address: ses.eth

### CODE REVIEW

**Comment by schmidsi** [comment]
It might be worth having a discussion about the other global commands. Here is my argumentation why I did not include other commands:

Generally, the root commands should:
a) Do root-level stuff like `postinstall` or `precommit`, or
b) Do stuff on multiple packages like `test` or `format`, or
c) Be part of the necessary happy path like `chain`, `deploy`, `start`

- "account" -> This is not necessarily needed. Could be seen as needed for chain deploys.
- "compile" -> Not needed, `deploy` also compiles
- "flatten" -> That is usually an edge-case for verification.
- "fork" -> Special use-case, not part of happy path
- "generate" -> Not needed, `deploy` also generates types and stuff
- "verify" -> Not part of happy path since there are multiple ways to verify contracts

**Comment by technophile-04** [comment]
Thanks @schmidsi! This canges makes sense! A coule of things which I feel we should do is: 

1. Remove the `echo 'Deprecated` messages in happy path commands. I think it's not worth it. 
2. Add `generate`, `account`, and `verify`, `fork` to happy path commands
3. Remove `yarn compile`, `yarn flatten` , `yarn hardhat-verify`. Instead we only have `hardhat:<command>` for all this commands
4. We sort the commands, Maybe the order could be: 
    1. Happy path commands first (chain, start, deploy, verify, generate, account, fork, vercel, vercel:yolo)
    3. commands that do stuff on multiple packages like test or format
    4. package specific command, maybe we keep all the hardhat:<commands> first
    5. All the `next:commands` second
    6. misc like postInstall, precommit.

**Comment by rin-st** [comment]
Thanks @schmidsi !

I agree with @technophile-04 mostly

> 4. We sort the commands, Maybe the order could be:

For my eye there will be no difference between `i` and `ii`, and also it requires remembering where `i`, where `ii` and where `v`

For me, alphabetical order for everything is good since it's easier for an eye to search the script and doesn't require to remember the order of groups

The second option could be
1. `hardhat:<command>` group
2. `next:<command>` group
3. everything else in alphabetical order

it almost doesn't require to remember order of groups too

**Comment by schmidsi** [comment]
I personally like the alphabetical ordering too: It's easy to reason about, like no discussion about "does this belong to happy path or misc"? Also, it looks pretty good and it groups the prefixed ones. This is what it looks like on my test repo:

```
"scripts": {
    "account": "yarn hardhat:account",
    "chain": "yarn hardhat:chain",
    "deploy": "yarn hardhat:deploy",
    "fork": "yarn hardhat:fork",
    "format": "yarn next:format && yarn hardhat:format",
    "generate": "yarn hardhat:generate",
    "graph": "yarn workspace @se-2/subgraph graph",
    "graphclient:build": "yarn workspace @se-2/nextjs client",
    "hardhat:account": "yarn workspace @se-2/hardhat account",
    "hardhat:chain": "yarn workspace @se-2/hardhat chain",
    "hardhat:check-types": "yarn workspace @se-2/hardhat check-types",
    "hardhat:compile": "yarn workspace @se-2/hardhat compile",
    "hardhat:deploy": "yarn workspace @se-2/hardhat deploy",
    "hardhat:flatten": "yarn workspace @se-2/hardhat flatten",
    "hardhat:fork": "yarn workspace @se-2/hardhat fork",
    "hardhat:format": "yarn workspace @se-2/hardhat format",
    "hardhat:generate": "yarn workspace @se-2/hardhat generate",
    "hardhat:hardhat-verify": "yarn workspace @se-2/hardhat hardhat-verify",
    "hardhat:lint": "yarn workspace @se-2/hardhat lint",
    "hardhat:lint-staged": "yarn workspace @se-2/hardhat lint-staged",
    "hardhat:test": "yarn workspace @se-2/hardhat test",
    "hardhat:verify": "yarn workspace @se-2/hardhat verify",
    "postinstall": "husky install",
    "next:build": "yarn workspace @se-2/nextjs build",
    "next:check-types": "yarn workspace @se-2/nextjs check-types",
    "next:format": "yarn workspace @se-2/nextjs format",
    "next:lint": "yarn workspace @se-2/nextjs lint",
    "next:serve": "yarn workspace @se-2/nextjs serve",
    "precommit": "lint-staged",
    "start": "yarn workspace @se-2/nextjs dev",
    "subgraph:abi-copy": "yarn workspace @se-2/subgraph abi-copy",
    "subgraph:clean-node": "yarn workspace @se-2/subgraph clean-node",
    "subgraph:codegen": "yarn workspace @se-2/subgraph codegen",
    "subgraph:create-local": "yarn workspace @se-2/subgraph create-local",
    "subgraph:local-ship": "yarn workspace @se-2/subgraph local-ship",
    "subgraph:run-node": "yarn workspace @se-2/subgraph run-node",
    "subgraph:stop-node": "yarn workspace @se-2/subgraph stop-node",
    "subgraph:test": "yarn workspace @se-2/subgraph test",
    "test": "yarn hardhat:test",
    "vercel": "yarn workspace @se-2/nextjs vercel",
    "vercel:yolo": "yarn workspace @se-2/nextjs vercel:yolo",
    "verify": "yarn hardhat:verify"
  },
  ```

@technophile-04 would you agree? Otherwise, let me know, I can also change to your proposed ordering. I don't have a strong opinion here.

**Comment by schmidsi** [comment]
It's probably also easier to compose multiple commands from multiple plugins together.

**Review by carletex — COMMENTED** [review]
This is looking sharp @schmidsi 

I think sorting alphabetically makes sense, so we don't have to think where to add new stuff.

A couple of things:

1. I'd personally miss the `yarn compile` happy path, but maybe it's just me.
2. This is probably for another PR/discussion, but: In the past, we've talked about having a global `yarn lint` command (lint everything + check-types). Same as `yarn lint-staged` but for the current state of your files (not only staged ones).

**Comment by schmidsi** [comment]
@carletex, thanks for the feedback. Added both. +1 for a global lint command.

**Review by technophile-04 — APPROVED** [review]
I think this looks great, Thanks!! A very small nitpick maybe we update "scripts" section of `packages/nextjs/package.json` and `packages/hardhat/package.json` too? Just so that everything follows same rule...very small thing but lol not sure in future when touch again the scripts sections of packages.json, so that's why trying to get it in this PR 🙌

**Comment by schmidsi** [comment]
@technophile-04 good point. I've sorted those alphabetical too. Rebased, force-pushed, let's merge that mfer in ;)

**Review by technophile-04 — APPROVED** [review]
Thanks @schmidsi! Looks great!

**Pull request merged**
