### PR TITLE
fix/update foundry branch

### PR DESCRIPTION
**Pull request by jrcarlos2000**
## Description

Addressing some errors , improvements in foundry branch

- [x] Fix bytecode opcode in `code` tab of blockexplorer.
- [x] Fix export deployment for custom networks ( networks that are not in stdChains of foundry )
- [x] Updated README
- [ ] 

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #394

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address: jrcarlos2000.eth

### CODE REVIEW

**Comment by jrcarlos2000** [comment]
Custom Networks `exportDeployments()` fails because it uses a list of `stdChains` and if your custom chain is not in the list, the script breaks.

So far in the case of custom networks, the user needs to use `exportDeployments("CustomNetworkName")`, that's the best and fastest solution I have found so far, been playing around with the different tools of the foundry library, however there are other ways to avoid this and get back to a single function exportDeployments()
- Similar to `ListAccount.s.sol`, iterate over available network with forks and compare chainId, however this will be very slow.
- Forget about network names and only use chainIds, this would still work in /nextjs package.

will keep tinkering about this problem. cc: @technophile-04

**Comment by technophile-04** [comment]
Tysm @jrcarlos2000 !! really appreciate it 🙌

> Fix bytecode opcode in code tab of blockexplorer.

Thanks, I was wondering if is there a way to put all contract's in `contracts` directory instead of `src`? We are trying hard to keep `foundry` branch similar to `hardhat`, So it would be great if we default all our contracts in `contracts` directory 🙌. maybe we update mapping `src = 'contracts'` in `foundry.toml` not sure 

---

> Custom Networks exportDeployments() fails because it uses a list of stdChains and if your custom chain is not in the list, the script breaks.

> So far in the case of custom networks, the user needs to use exportDeployments("CustomNetworkName"), that's the best and fastest solution I have found so far, been playing around with the different tools of the foundry library, however there are other ways to avoid this and get back to a single function exportDeployments()

Regarding this you mean to say if people add custom chain in `foundry.toml` which is not mentioned here [stdChains](https://github.com/foundry-rs/forge-std/blob/ff4bf7db008d096ea5a657f2c20516182252a3ed/src/StdCheats.sol#L230)   eg. `zetaChain` and then do `yarn deploy zetaChain` it will break? 

And if you want to work you need to call extra function after this : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/d5c1366484c2808e8b35eecbe2d01d11cefce2d4/packages/foundry/script/Deploy.s.sol#L21

Like `exportDeployments("zetaChain")`? 

I would say let's keep this for other PR, could you just mention this problem in #394 and handle it in a separate PR? 

---

Also we recently migrated ListAccount.s.sol -> `.js` in #437, so I see there is some conflict in `packages/foundry/package.json` could you please solve it 🙌

**Comment by jrcarlos2000** [comment]
> Thanks, I was wondering if is there a way to put all contract's in contracts directory instead of src? We are trying hard to keep foundry branch similar to hardhat, So it would be great if we default all our contracts in contracts directory 🙌. maybe we update mapping src = 'contracts' in foundry.toml not sure

Yes, that is possible !

Noted on the rest!

**Comment by jrcarlos2000** [comment]
>Like exportDeployments("zetaChain")?
I would say let's keep this for other PR, could you just mention this problem in https://github.com/scaffold-eth/scaffold-eth-2/issues/394 and handle it in a separate PR?

The current implementation has overloaded functions so we can work on improving that mechanism in future PRs
cc: @technophile-04

**Comment by technophile-04** [comment]
Tysm @jrcarlos2000 🙌, just tested and looks great !! 

- Added some comments for the `exportDeployments` function 
- Added gnosis chain for fixing #341 
- add the comments for YourContract.sol

**Pull request merged**
