### PR TITLE
feat: display eth price as per target network

### PR DESCRIPTION
**Pull request by kevinjoshi46b**
Solves #323

My matic balance:
image

My USD balance for the same:
image

# Discussion

For `arbitrum` and `fantom` uniswap SDK is unable to fetch data and throws an error. The price is shown on uniswaps dapp not sure how but maybe they are using coinbase's api for it. Current solution:
1. Remove the tokenAddresses for these two chains and the price for these chains won't be displayed and there won't be any error
2. Let the error be thrown in the terminal

### CODE REVIEW

**Comment by damianmarti** [comment]
> Solves #323
> 
> My matic balance: image
> 
> My USD balance for the same: image
> 
> # Discussion
> For `arbitrum` and `fantom` uniswap SDK is unable to fetch data and throws an error. The price is shown on uniswaps dapp not sure how but maybe they are using coinbase's api for it. Current solution:
> 
> 1. Remove the tokenAddresses for these two chains and the price for these chains won't be displayed and there won't be any error
> 2. Let the error be thrown in the terminal

I vote for option 1!

**Comment by carletex** [comment]
Good job @kevinjoshi46b , thanks :)

Left a couple of comments. Also let's merge this into #323

**Comment by kevinjoshi46b** [comment]
> Left a couple of comments. Also let's merge this into #323

Yup will resolve everything here and then rebase into #323, also what are your opinions on `Discussion` section [here](https://github.com/scaffold-eth/scaffold-eth-2/pull/324#issue-1681015329)

**Comment by kevinjoshi46b** [comment]
Oh wait its #322 not #323 :)

**Comment by kevinjoshi46b** [comment]
Rebased into #322

**Pull request closed without merging**
