### PR TITLE
Add copy to clipboard to TxReceipt

### PR DESCRIPTION
**Pull request by damianmarti**
## Description

Add copy to clipboard to transaction receipt to allow to copy the transaction data easily.

localhost_3002_debug

## Additional Information

- [X] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [X] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: damianmarti.eth

### CODE REVIEW

**Review by technophile-04 — APPROVED** [review]
Nice !! LGTM ! 

Thanks @damianmarti 🙌

**Comment by carletex** [comment]
Nice! Thanks @damianmarti 

The only thing that I'd explore is to position the copy icon in a different place (rn It feels a bit in the middle of nowhere)

The standard seems to be on the top right, but since we already have the arrow, might look a bit weird:
image

Another option could be next to the title:
image

We'd have to tweak a bit since that whole "row" collapses the result on click.

---

Anyway, just a suggestion, not a big deal if we keep it as it is!

**Comment by damianmarti** [comment]
@carletex yeah, I know, it's not the best place.

Next to the title is the best option, but we should remove the row collapse by clicking the header and moving it to only the arrow.

I will try it!

**Comment by damianmarti** [comment]
@carletex what do you think now?

localhost_3002_debug (1)

The receipt is copied by clicking the copy icon and the receipt is expanded if you click anywhere else.

localhost_3002_debug (2)

**Review by rin-st — APPROVED** [review]
lgtm!

**Comment by carletex** [comment]
Thanks @damianmarti !!!

I think this looks better.

**Pull request merged**
