### PR TITLE
Fix vercel deployment mismatch

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

My 99th try of trying to fix this. 

context #419 and all referenced PR inside it. 

Obviously there is a catch, had to add `next` as devDependency of monorepo because of https://github.com/orgs/vercel/discussions/6047 but now atleast it uploads whole monorepo (mainly `yarn.lock`) which fixes all the issues

Work flow doesn't change at all you just need to choose all defualt options and add vercel project : 

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/32a76d20-c6e2-49fc-9072-bdac9f7a947b

### CODE REVIEW

**Comment by carletex** [comment]
> My 99th try of trying to fix this.

hahaha Thanks for this @technophile-04 great stuff.,

> Obviously there is a catch, had to add next as devDependency of monorepo

I can live with this haha. This is a great solution. 

All good for me. Let's see if @Pabl0cks can test on Windows for final confirmation

**Review by Pabl0cks — APPROVED** [review]
`yarn vercel` is working great on Windows too, 

<details>
<summary>Bash output sshot</summary>

image

</details>


Great job, TYSM Shiv!

**Review by rin-st — APPROVED** [review]
🙌

**Comment by technophile-04** [comment]
Thanks all merging this 🙌

**Pull request merged**
