### PR TITLE
Remove clone command + add npx install

### PR DESCRIPTION
**Pull request by carletex**
As we discussed yesterday, we are moving away from SE-2 clone method. The first step is to remove it from the docs / READMEs / etc.

Related https://github.com/scaffold-eth/scaffoldeth.io/pull/41

### CODE REVIEW

**Review by technophile-04 — COMMENTED** [review]
Currently the below commands are hardhat specific 

 https://github.com/scaffold-eth/scaffold-eth-2/blob/e5a666b78c5f7c8dfc8f827643128612dd23c71f/README.md?plain=1#L46 
 
Umm maybe make description for those 3 magic commands a bit more generic and then point to docs directly? 
\

**Comment by Pabl0cks** [comment]
> Umm maybe make description for those 3 magic commands a bit more generic and then point to docs directly?

Sounds good, I can tweak them if you want

**Comment by Pabl0cks** [comment]
> Sounds good.

Tried to remove all the references to specific configuration of Hardhat, and pointed to the docs instead. Also pushed a couple of small tweaks:
- Add foundry to tech stack
- Add extensions hint in installation setup

Let me know if you prefer to remove any of that, or go more minimal in the Readme. Thanks! 🙌

**Review by technophile-04 — APPROVED** [review]
Thanks! I think this looks great for first iteration!

**Pull request merged**
