### PR TITLE
Up next react sept 24

### PR DESCRIPTION
**Pull request by rin-st**
## Description

Step 2 of https://github.com/scaffold-eth/scaffold-eth-2/pull/917#issuecomment-2320138630

Decided to combine next/react with CSS libs or we will have 15 pull requests just to update dependencies

Plus
- updated `react-copy-to-clipboard` types since it's broken with newest react
- updated `vercel` version
- updated `viem`, `wagmi` and `rainbowkit` last patches

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

### CODE REVIEW

**Comment by rin-st** [comment]
Note: need to update all the pr related libs again before test/merge

**Comment by technophile-04** [comment]
> Note: need to update all the pr related libs again before test/merge

Yup makes sense! Thanks @rin-st! Will review/test it as soon you push the update commit, also no rush at all!!

**Comment by rin-st** [comment]
> Yup makes sense! Thanks @rin-st! Will review/test it as soon you push the update commit, also no rush at all!!

Updated!

**Review by Pabl0cks — APPROVED** [review]
GJ @rin-st !! 🙌 Tested in [vercel-sepolia](newreceipt.vercel.app) and is working nicely to me.

In the [vercel development site](https://newreceipt-f9dgyv03d-tokodevs-projects.vercel.app/) at some point I checked console and I was getting spamming errors, (I think they're related to Metamask) but I haven't noticed any bad behaviour. 

image

Will try to reproduce later tonight, I tried a couple times and couldn't reproduce 🙏

**Comment by rin-st** [comment]
Thank you for testing! I cannot access second link and check it (I don't need it if no errors)
image

> Will try to reproduce later tonight, I tried a couple times and couldn't reproduce 🙏

Tried to reproduce it too, no luck

**Comment by rin-st** [comment]
wrote `lockdown-install.js` to google and every link tells that it's because of metamask. For example [here](https://stackoverflow.com/questions/76393186/what-is-causing-the-warning-removing-intrinsics-arrayprototype-toreversed-in)

**Comment by Pabl0cks** [comment]
I couldn't reproduce it either, so maybe it was some random error from my metamask. 

Trying to reproduce it i realized the collapse icon is not showing in the right place in /debug `txReceipt`.

<details><summary>Screenshot</summary>

image
</details>

**Comment by rin-st** [comment]
> Trying to reproduce it i realized the collapse icon is not showing in the right place in /debug txReceipt. 

Fixed it + arrow in tuple arrays

before: 

Screenshot 2024-09-16 at 12 07 38

after:

Screenshot 2024-09-16 at 13 06 21


<details><summary>Contract to test</summary>
<p>

```pragma solidity ^0.8.0;

contract TestContract {
	struct Data {
		uint256 id;
		string name;
	}

	// Method with a struct parameter
	function methodWithTuple(
		Data memory data
	) public pure returns (uint256, string memory) {
		return (data.id, data.name);
	}

	// Method with an array of struct parameter
	function methodWithArrayOfTuples(
		Data[] memory dataArray
	) public pure returns (Data[] memory) {
		return dataArray;
	}
}
```

</p>
</details> 

<details><summary>Deployment file</summary>
<p>

```
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { DeployFunction } from "hardhat-deploy/types";

const deployTestContract: DeployFunction = async function (hre: HardhatRuntimeEnvironment) {
  const { deployer } = await hre.getNamedAccounts();
  const { deploy } = hre.deployments;

  await deploy("TestContract", {
    from: deployer,
    args: [],
    log: true,
    autoMine: true,
  });
};

export default deployTestContract;

deployTestContract.tags = ["TestContract"];


```
</p>
</details>

**Review by technophile-04 — APPROVED** [review]
Thanks @rin-st !! Tested it nicely and works great! 

https://up-next-psi.vercel.app/

> I was getting spamming errors, (I think they're related to Metamask) but I haven't noticed any bad behaviour.

Ohh I have kind of seen this sometime not sure why its happens but I think it happens only in rare cases that to on vercel gated URL's on actual open to all domains haven't encountered it. So feel nothing to very that much about but we could keep a look and tackle it sometime

**Pull request merged**
