### PR TITLE
Remove ExampleUI (pages, components, assets, content)

### LINKED ISSUE #576: (Re)move Example UI
Following feedback from some people and for the sake of keeping the codebase lighter, let's discuss what we can do with Example UI.

The idea behind it was to show beginners how to use SE2 (components, hooks, styling, etc), but I don't think it has been very useful for that purpose. Also, types break the moment you start tweaking the contract, and it's something you have to remove when deploying.

I see a couple of options:

1. Remove it completely and create a good Recipes section in the SE-2 docs, where people can copy-paste examples that work out of the box. This is what most libraries/starter kits do. I already created the issue: https://github.com/scaffold-eth/se2-docs/issues/25, since the "Recipes" section is something that we wanted to do anyway.
2. Add it in as an extension for the CLI. People could opt in if they want. "Would you like an example UI that shows how to style and use hooks?"

My vote is **1**, since I don't like cluttering the CLI options with this, something that I feel it's not that important / useful.

Let's hear what you all think!

### PR DESCRIPTION
**Pull request by carletex**
Fixes #576 

This feels good haha. Please check that I'm not missing anything that ExampleUI was using and I didn't remove.

We could wait to merge this until we have a v0.1 of https://github.com/scaffold-eth/se2-docs/issues/25.... or not :innocent:

P.S. Shoutout to @rin-st who did a great job implementing it in the first place :)

### CODE REVIEW

**Comment by damianmarti** [comment]
@carletex I found a small comment about the example UI in the README page:

> Visit your app on: http://localhost:3000. You can interact with your smart contract using the contract component or the example ui in the frontend.

**Comment by carletex** [comment]
> I found a small comment about the example UI in the README page:

Good catch Damu!

Removed it on https://github.com/scaffold-eth/scaffold-eth-2/pull/578/commits/f3486b56f5646f42862b288387abd6734369921f

**Review by technophile-04 — APPROVED** [review]
We can remove `react-fast-marquee` https://github.com/scaffold-eth/scaffold-eth-2/blob/aec2b8cb225a3f40f9ed25f7364347c43d20e944/packages/nextjs/package.json#L30

and maybe this rule too ( not sure about this weather to keep this or not) : 
https://github.com/scaffold-eth/scaffold-eth-2/blob/aec2b8cb225a3f40f9ed25f7364347c43d20e944/packages/nextjs/.eslintrc.json#L14


apart from this I think everything is removed 🙌


---


> This feels good haha. Please check that I'm not missing anything that ExampleUI was using and I didn't remove.
> 
> We could wait to merge this until we have a v0.1 of [scaffold-eth/se2-docs#25](https://github.com/scaffold-eth/se2-docs/issues/25).... or not 😇

I think maybe we could merge this 🙌 since we already have all isolated examples of hooks in docs.... not that verbose how it will be recipe section but I think they are good 


> P.S. Shoutout to @rin-st who did a great job implementing it in the first place :)

🫡🫡

Tysm Carlos 🙌

**Review by damianmarti — APPROVED** [review]
LGTM! Thanks, @carletex !!

**Review by rin-st — APPROVED** [review]

**Comment by rin-st** [comment]
Looks good to me!
F 🫡

**Comment by carletex** [comment]
Good eye @technophile-04 !! Remove the lib and the eslint rule.

Thanks all for the review!

I'll let you guys merge after reviewing the last two commits :)

**Comment by technophile-04** [comment]
LGTM!  Tysm Carlos and all for reviews !! Merging this 🙌

**Pull request merged**
