### PR TITLE
Ethers v6 migration in hardhat

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

Recently we updated all the hardhat related packages in #637, but it seems that if you uncomment : 

https://github.com/scaffold-eth/scaffold-eth-2/blob/e4c70071ae804f88d4d73662d8e1b52ea7e833bd/packages/hardhat/deploy/00_deploy_your_contract.ts#L35

You get an error, which I think is caused due to `hardhat-deploy-ethers` and `hardhat-ethers`  digging few discussion it seems that updating ethers to v6 does seems to solve this issue due to some internal api changes

### CODE REVIEW

**Comment by technophile-04** [comment]
Tysm all !! I think after #692 we could merge this 🙌

**Comment by rin-st** [comment]
Works great!

> Tysm all !! I think after https://github.com/scaffold-eth/scaffold-eth-2/pull/692 we could merge this 🙌

recursion 😄

**Review by rin-st — APPROVED** [review]

**Comment by carletex** [comment]
> recursion 😄

lol 

Great job @technophile-04. Add uncommented example code as we talked on TG.

Let's also add this to the weekly CLI merge.

**Comment by technophile-04** [comment]
> recursion 😄 

😂 lol my bad wanted to add that comment at #685

**Pull request merged**
