### PR TITLE
Add prettier-plugin-tailwindcss to sort tailwindcss classes

### PR DESCRIPTION
**Pull request by portdeveloper**
## Description

This PR adds prettier-plugin-tailwindcss to scaffold-eth-2. 
By using prettier-plugin-tailwindcss, this PR aims to achieve consistency in classNames across projects using scaffold-eth-2.
Also, all necessary files that contain tailwind classes are sorted.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

Your ENS/address: portdev.eth

### CODE REVIEW

**Comment by portdeveloper** [comment]
Getting this error when I format a file, also it takes too long to format. 

`[Error - 2:17:14 PM] An unexpected error occurred:
[Error - 2:17:14 PM] Error: Cannot find module '@trivago/prettier-plugin-sort-imports'
Require stack:
- C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\prettier\index.js
- C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-plugin-prettier\eslint-plugin-prettier.js
- C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\@eslint\eslintrc\dist\eslintrc.cjs
Occurred while linting C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\pages\debug.tsx:1
Rule: "prettier/prettier"
    at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)
    at mod._resolveFilename (C:\Users\port\testrepos\scaffold-eth-2\packages\nextjs\node_modules\eslint-config-next\index.js:49:26)`

**Comment by portdeveloper** [comment]
Seems like the official Tailwind CSS Intellisense vscode extension is the cause of this slowness, not ESLint. I disabled that extension and now everything works fine. 
I would like other people to test this as well.

**Comment by rin-st** [comment]
Hey @portdeveloper, thanks for pr!
I have Tailwind intellisense extension, and for me everything works and works fast. We need to figure out why it's slow for you because disabling the extension for everyone is not the best solution

**Comment by portdeveloper** [comment]
Thanks for the insight. I am glad to hear that it is working out great for you! I think there might be a problem with my machine...

**Comment by technophile-04** [comment]
Tysm Port and Rinnat 🙌

I tried this on `vscode` with tailwind intellisense installed and it works fine for me 🙌


NOTE : My `nvim` lsp config is a bit messed up, so just sharing my personal problem when I was try to format in `nvim` it was adding some `daisUI` stuff at the top of the file after formatting :

https://github.com/scaffold-eth/scaffold-eth-2/assets/80153681/ae4d33f0-d6e7-4bb2-a149-7da02715702e

After researching some, I found this discussion: 

1. Doing `daisyUi.logs : false` in `tailwind.config.js` solved the issue for me as suggested here -> https://github.com/tailwindlabs/tailwindcss/discussions/8380#discussion-4083131

2. Its seems that `prettier-plugin-tailwindcss` had some incompatibilities with `@trivago/prettier-plugin-sort-imports` (which we are using....port also got kind of same error https://github.com/scaffold-eth/scaffold-eth-2/pull/393#issuecomment-1614547337 ).......check out this discussion about this issue: 
    1. https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/9 
    2. Although the above issue's was fixed I found people people still using some workaround like : 
https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/31#issuecomment-1448996271 also worth checking full discussion
     3. Also regarding Port's this comment https://github.com/scaffold-eth/scaffold-eth-2/pull/393#issuecomment-1615145199  while researching I found a person who had same issue and he resolved it by uninstalling and installing tailwind extention :), I am unable to find it now but it might be somewhere hidden here ->  https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/113

**Comment by portdeveloper** [comment]
One thing I noticed about prettier-plugin-tailwindcss is that it does not remove extra whitespaces in the classNames, and sometimes it just changes the places of two classes over and over again. This will hinder standardization.
I will open an issue on their github and see if they can fix it.

**Comment by technophile-04** [comment]
> Sometimes it just changes the places of two classes over and over again. This will hinder standardization

Yeah, I have noticed sometimes this issue too !! 

Due to some issues in the plugin and also, I went through a few discussion's on this, and seems like not everyone likes it 

Obviously, this is considered as best practice to have in "tailwind zone" but I think it not worth adding at the moment in SE-2 😅 due to some issues, maybe in future in se-2-docs if we have a section regarding best-practices/ extra tools we are for sure gonna recommend this !! 

But tysm @portdeveloper for this, really appreciate it !!

**Comment by Pernick** [comment]
> One thing I noticed about prettier-plugin-tailwindcss is that it does not remove extra whitespaces in the classNames, and sometimes it just changes the places of two classes over and over again.

Has anyone found a fix for this? This issue makes it really hard to use format check in CI.

At this point I've tried everything mentioned in this PR and some other things to no avail:
* reinstall VSCode extensions (tailwind, prettier)
* remove `@trivago/prettier-plugin-sort-imports`
* try different prettier/prettier plugin versions with different import styles

> I will open an issue on their github and see if they can fix it.

Did you find time to do this? Couldn't find any issues you authored.

**Comment by portdeveloper** [comment]
> > One thing I noticed about prettier-plugin-tailwindcss is that it does not remove extra whitespaces in the classNames, and sometimes it just changes the places of two classes over and over again.
> 
> Has anyone found a fix for this? This issue makes it really hard to use format check in CI.
> 
> At this point I've tried everything mentioned in this PR and some other things to no avail:
> 
> * reinstall VSCode extensions (tailwind, prettier)
> * remove `@trivago/prettier-plugin-sort-imports`
> * remove daisyUI logs
> * try different prettier/prettier plugin versions with different import styles
> 
> > I will open an issue on their github and see if they can fix it.
> 
> Did you find time to do this? Couldn't find any issues you authored.
> 
> I **failed to replicate** this issue with new Next.js + DaisyUI + Tailwind + ESLint + Prettier (w/ @trivago/prettier-plugin-sort-imports and prettier-plugin-tailwindcss) even with the exact versions and configs, wondering whether it has something to do with the monorepo structure. I'll post an update here if I figure it out.

I didn't open an issue and basically forgot about it. I think there is a vscode extension that does the same thing. If one day, there exists a solution for this that could be added to a CI/CD pipeline of a project, it will be great as a lot of the devs i saw, including me, just dont care about the order of tailwind classes.

**Comment by Pernick** [comment]
Adding this in case someone who struggles with this stumbles on this:

My issue was that I was using `tailwind.config.ts` instead of `tailwind.config.js` and in that case the prettier config needs to point the prettier plugin to the correct config with this:

```
"tailwindConfig": "./tailwind.config.ts"
```

**Pull request closed without merging**
