### PR TITLE
New commands to deploy on smart contract change

### PR DESCRIPTION
**Pull request by ByteAtATime**
## Description

Add the following commands, both of which watch `packages/hardhat/contracts` and `packages/hardhat/deploy` for changes:
- `deploy:watch` - on change, run `yarn deploy`
- `deploy:watch-reset` - on change, run `yarn deploy --reset`

Watching files is done through the [`watch`](https://npmjs.com/package/watch) package.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

Minor QoL change, didn't file an issue

Your ENS/address: `0x3848457d61094F13Cbd6Fc4cf8D6383C48506232`

### CODE REVIEW

**Comment by ByteAtATime** [comment]
I'm not sure what the CONTRIBUTING.md means by "tag a maintainer" so... @carletex?

**Comment by carletex** [comment]
Hey @ByteAtATime 

Thanks for taking your time on this PR.

[Hardhat deploy](https://github.com/wighawag/hardhat-deploy) already have both flags, so ideally we don't want to bloat the repo with extra commands (and new libs) that we don't really need.

`yarn deploy --reset` works, but I noticed that `yarn deploy --watch` works (detects changes in contracts/ and deploy/)... BUT doesn't run the `generateTsAbis` script. It's because the `--watch` doesn't let the deploy command exit.

We should find a fix for that!

**Comment by ByteAtATime** [comment]
Oh, sorry, I didn't know it had the command, probably should've taken more time with this. I'm going to close this PR and open a new one if I find the solution.

**Comment by ByteAtATime** [comment]
@carletex  I believe that we can make a separate script that uses `fs.watch` (node stdlib). However, this might not offer the best experience. Here's an example I made:

```ts
const fs = require('fs');
const { run } = require('hardhat');

async function main() {
  // Deploy your contracts using Hardhat
  const contracts = await run('deploy');

  // Generate the ABI types
  await run('generateTypes');

  // Watch for changes and redeploy if necessary
  if (process.argv.includes('--watch')) {
    fs.watch('./contracts', { recursive: true }, async () => {
      console.log('Changes detected. Redeploying...');
      await run('deploy');
      await run('generateTypes');
    });
  }
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

The problem with this is that there's likely many quality of life features that hardhat's watch has implemented, and using this would lose them.

**Pull request closed without merging**
