### PR TITLE
(docs) Fixed the main frontend path in README

### PR DESCRIPTION
**Pull request by kkomelin**
## Description

Previously the main frontend path was `nextjs/pages`. Now the project switched to the Next.js App Router and the `nextjs/app` folder correspondingly. We need to update the README correspondingly.

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

### CODE REVIEW

**Review by Pabl0cks — COMMENTED** [review]
Good catch @kkomelin!! We updated it in [docs](https://github.com/scaffold-eth/se2-docs) but totally missed README!

In docs we changed the "Edit your frontend" line for:

- Edit your frontend homepage at `packages/nextjs/app/page.tsx`. For guidance on [routing](https://nextjs.org/docs/app/building-your-application/routing/defining-routes) and configuring [pages/layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) checkout the Next.js documentation.

Maybe we could use same explanation?

**Comment by rin-st** [comment]
> In docs we changed the "Edit your frontend" line for:

[Link](https://docs.scaffoldeth.io/quick-start/environment#whats-next)

@Pabl0cks what do you think about adding "Edit your smart contract tests" too? (hh part)

**Comment by kkomelin** [comment]
@Pabl0cks @rin-st Thanks for your time reviewing my PR. Feel free to edit my PR the way you think reasonable.

**Comment by Pabl0cks** [comment]
> @Pabl0cks what do you think about adding "Edit your smart contract tests" too? (hh part)

Yeah we can add it! Would love to check if it was not added for simplicity or if it's cool to add it with @carletex or @technophile-04  

Maybe we can format it similarly to the docs as:

### What's next

- Edit your smart contract `YourContract.sol` in `packages/hardhat/contracts`
- Edit your frontend homepage at `packages/nextjs/app/page.tsx`. For guidance on [routing](https://nextjs.org/docs/app/building-your-application/routing/defining-routes) and configuring [pages/layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) checkout the Next.js documentation.
- Edit your deployment scripts in `packages/hardhat/deploy`
- Edit your smart contract test in: `packages/hardhat/test`. To run test use `yarn hardhat:test`

**Comment by technophile-04** [comment]
>  if it was not added for simplicity

Not remember completely but might be the reason, since we already had docs link below it 

But thinking a bit maybe we could add it what @Pabl0cks suggested (since we already have most of the points already present) 

Maybe we should keep "What's next" small (maybe bold) but not as heading 

Something like : 

<details>
<summary>
Demo : 
</summary>

Screenshot 2024-04-12 at 9 59 01 PM


</details>

<details>
<summary>
Code : 
</summary>

```shell
**What's next**:

- Edit your smart contract `YourContract.sol` in `packages/hardhat/contracts`
- Edit your frontend homepage at `packages/nextjs/app/page.tsx`. For guidance on [routing](https://nextjs.org/docs/app/building-your-application/routing/defining-routes) and configuring [pages/layouts](https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts) checkout the Next.js documentation.
- Edit your deployment scripts in `packages/hardhat/deploy`
- Edit your smart contract test in: `packages/hardhat/test`. To run test use `yarn hardhat:test`
```

</details>

@kkomelin  could you please update it?

**Comment by Pabl0cks** [comment]
> Maybe we should keep "What's next" small (maybe bold) but not as heading

Yes! Totally. After sending my sample I was like.. maybe too big 😅

**Comment by kkomelin** [comment]
I'm on it guys, will update soon.

**Comment by kkomelin** [comment]
@technophile-04 @Pabl0cks Just applied your suggested changes. Please review

**Review by technophile-04 — APPROVED** [review]
Thanks @kkomelin ! and also thanks all for great suggestions !

**Comment by kkomelin** [comment]
Thanks everyone for helping with that!

**Pull request merged**
