### PR TITLE
Cli weekly backmerge

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

- Extract metadata title and description (#770)
- Remove Goerli from supported networks (#771)
- fix: redundant error notifications on block explorer (#775)
- chore: fix typo (#777)
- fix: vercel deployment linking from github (#780)
- Remove useAccountBalance (#788)
- Templatise README in CLI (#790, #782) 
- Add .env to .gitignore in nextjs package (#798)

### CODE REVIEW

**Review by technophile-04 — COMMENTED** [review]
Tested nicely and everything does seem to work, but would love if someone just give a try 🙌

**Comment by rin-st** [comment]
deployment works for me, but

gh-actions fail for new foundry project. I think it's already known bug? 
[example](https://github.com/rin-st/bmtest1/actions/runs/8575362148/job/23504173687)

**Comment by technophile-04** [comment]
> gh-actions fail for new foundry project. I think it's already known bug?

Ohh yup, we do have an open issue for it #607

**Review by rin-st — APPROVED** [review]

**Comment by rin-st** [comment]
> Ohh yup, we do have an open issue for it https://github.com/scaffold-eth/scaffold-eth-2/issues/607

Got it, thanks!

**Comment by technophile-04** [comment]
Thanks @rin-st, Merging this 🙌

**Pull request merged**
