### PR TITLE
fix: vercel deployment linking from github

### PR DESCRIPTION
**Pull request by technophile-04**
## Description

After we merged #757 , it seems to broke the vercel deployment when you connect it through github example : 
github.com/technophile-04/test-vercel-deployments

Screenshot 2024-03-17 at 1 31 32 PM

This is because we are mentioning `outputDir` in `vercel.json` which is different when you connect through github

### CODE REVIEW

**Comment by rin-st** [comment]
How to test it properly?
- Cloned main repo (add third party repo option), added it from vercel dashboard - deployment works already from main branch
- `npx create-eth@latest` hardhat - same error on main branch, and same error when I add your changes.

**Comment by technophile-04** [comment]
> added it from vercel dashboard - deployment works already from main branch

This should actually fail, If you try doing : 

Screenshot 2024-03-18 at 12 51 56 PM


And then connecting the repo to vercel it gives the above error. For example I tried doing same [here](https://github.com/technophile-04/test-vercel-deployments)

> npx create-eth@latest hardhat - same error on main branch, and same error when I add your changes.

I just did `npx create-eth@latest hardhat` and added this changes to it and it worked for [example here](https://github.com/technophile-04/npx-vercel-deployment)

--- 

### Testing these changes : 

Maybe you could "Create a new template" and then push this PR changes to your repo of `main` branch and connect to github

**Comment by rin-st** [comment]
Thank you! Tried both cases and everything works like you said.

> Cloned main repo (add third party repo option), added it from vercel dashboard - deployment works already from main branch

But after adding se-2 as a third party repo from vercel, deployment still works for main. I think it's not a problem though

Gj!

**Review by rin-st — APPROVED** [review]

**Comment by damianmarti** [comment]
@technophile-04 I was able to deploy to Vercel with no issues!

**Comment by Pabl0cks** [comment]
Tested after merge and is working great for me, gj @technophile-04! 🙌

**Pull request merged**
