### PR TITLE
move 99_deployScript as hardhat task

### PR DESCRIPTION
**Pull request by technophile-04**
### Description: 

This is something which we did at CTF repo. Doing this no more requires `99_deployScript` to be present and also avoids the problem people deleting it by mistake

### CODE REVIEW

**Review by carletex — APPROVED** [review]
Smart tweak :)

**Review by rin-st — APPROVED** [review]

**Comment by technophile-04** [comment]
Thanks guys! Merging this 🙌

**Comment by damianmarti** [comment]
@technophile-04 nice!! 

So the generateTsAbis script is run always you deploy now and you don't have to add the generateTsAbis tag anymore (it does not exist anymore), right? The abis are always generated after any deployment...

**Comment by technophile-04** [comment]
> you don't have to add the generateTsAbis tag anymore (it does not exist anymore), right? 

yeah that's the main reason 🙌 So now if people want to run a particular deploy script then can just do `yarn deploy --tags solution2` earlier they had to mention `generateTsAbis` tag too like `yarn deploy --tags solution2, generateTsAbis`

**Pull request merged**
